#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title open other window
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖

# Documentation:
# @raycast.author mozumasu
# @raycast.authorURL https://raycast.com/mozumasu

echo "Hello World!"

