add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
$directory\
$git_branch\
$git_status\
$direnv\
$python\
$fill\
$cmd_duration\
$time\
\n$character\
"""

# Enable if it appears on the same line as the command
# right_format = """
# $cmd_duration\
# $time\
# """

# ----------------------------------------------------
# left module
# ----------------------------------------------------
[python]
format = """
[](fg:#ffcb6b)\
[$virtualenv]($style)\
[](fg:#ffcb6b)\
"""
style = "bold fg:#313244 bg:#ffcb6b"

[fill]
symbol = '─'

[directory]
truncation_length = 6
truncation_symbol = ' '
truncate_to_repo = false
home_symbol = '~'
read_only = ' 󰌾 '
format = """
[](fg:#e4d2d8)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#e4d2d8)\
"""
style = 'bold fg:#313244 bg:#e4d2d8'
read_only_style = 'bold fg:#e4d2d8 bg:#313244'

[direnv]
disabled = false
format = """
[](fg:#89dceb)\
[$symbol$allowed]($style)\
[](fg:#89dceb)\
"""
style = "bold fg:#313244 bg:#89dceb"

[git_branch]
symbol = ""
style = "fg:#313244 bg:#a6c8b2"
format = """
[](fg:#a6c8b2)\
[$symbol $branch]($style)\
"""

[git_status]
style = "fg:#313244 bg:#a6c8b2"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#a6c8b2)\
"""

# ----------------------------------------------------
# right module
# ----------------------------------------------------
[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[ $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# format = '[[  $time](fg:#313244)]($style)'
format = '[  $time](fg:#8fae92)'
# ----------------------------------------------------
# prompt module
# ----------------------------------------------------
[character]
# vimcmd_symbol = '[V](bold green) '
success_symbol = '[❯](bold fg:#a6c8b2)'
error_symbol = '[❯](bold fg:#f5b1aa)'
vimcmd_symbol = '[V](bold fg:#3a3f5a)'
