#!/usr/bin/env zsh
# https://rcmdnk.com/blog/2014/07/20/computer-vim/

local p="$PAGER"
local m="$MANPAGER"
local val ret

unset PAGER
unset MANPAGER

val=$(command man "$@" 2>&1)
ret=$?

if [ $ret -eq 0 ]; then
  printf '%s\n' "$val" | col -bx | nvim -R -c 'set ft=man' -
else
  printf '%s\n' "$val"
fi

if [ -n "$p" ]; then
  export PAGER="$p"
fi
if [ -n "$m" ]; then
  export MANPAGER="$m"
fi

return $ret
