#!/usr/bin/env zsh
# https://rcmdnk.com/blog/2014/07/20/computer-vim/

local p
local m
if [ "$PAGER" != "" ];then
  p="$PAGER"
fi
if [ "$MANPAGER" != "" ];then
  m="$MANPAGER"
fi
unset PAGER
unset MANPAGER
val=$(command man $@ 2>&1)
ret=$?
if [ $ret -eq 0 ];then
  echo "$val"|col -bx|nvim -R -c 'set ft=man' -
else
  echo "$val"
fi
if [ "$p" != "" ];then
  export PAGER="$p"
fi
if [ "$m" != "" ];then
  export MANPAGER="$m"
fi
return $ret
